### ISSUE TITLE
Running inverter example simulation segfaults

### ISSUE THREAD

**Issue by dannydarvish** [purdue-onchip/gds2Para#9]
Built on macOS 10.14.6. Everything runs up to `portSet time is ... s`, then I get

```
LayoutAnalyzer(1487,0x11fd285c0) malloc: can't allocate region
*** mach_vm_map(size=321850005830209536) failed (error code=3)
LayoutAnalyzer(1487,0x11fd285c0) malloc: *** set a breakpoint in malloc_error_break to debug
LayoutAnalyzer(1487,0x11fd285c0) malloc: can't allocate region
*** mach_vm_map(size=321850005830209536) failed (error code=3)
LayoutAnalyzer(1487,0x11fd285c0) malloc: *** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11
```

**Comment by ShuzhanSun** [comment]
Hi Danny,

Thank you for your interest in our package!

I just run the inverter example in our server (Linux OS, 128 GB memory, latest gds2Para master branch). The example can successfully run through and gave such logs 
[logInv_fineMesh.txt](https://github.com/purdue-onchip/gds2Para/files/5982844/logInv_fineMesh.txt)


The error you met with "malloc" is because your laptop does not have enough memory. What you can do is using a coarser mesh by tuning the parameters in "fdtd.hpp":

Current mesh parameters in master branch is targeted for 7-nm technology node, therefore give too many unknowns (N_edge   = 38,220,217) for inverter example.  
```C++
#define MINDISFRACX (1e-4) 
#define MINDISFRACY (1e-4) 
#define MINDISFRACZ (0.05) 
#define MAXDISFRACX (0.001) 
#define MAXDISFRACY (0.001)
#define MAXDISLAYERZ (2.)
```

You can use a coarse mesh with less edges by setting like below, which will give N_edge   = 156,222. The results are very similar to fine-mesh results. The log file is also attached as 
[logInv_coarseMesh.txt](https://github.com/purdue-onchip/gds2Para/files/5982846/logInv_coarseMesh.txt)

```C++
#define MINDISFRACX (0.01) 
#define MINDISFRACY (0.01) 
#define MINDISFRACZ (0.05) 
#define MAXDISFRACX (0.05) 
#define MAXDISFRACY (0.05)
#define MAXDISLAYERZ (2.)
```

Right now, we have not fully automated the adaptive mesh. That's why users may need to tune above hyper-parameters in the code. 

Also, our package has never been tested in macOS. So, you may encounter unexpected error later. I would suggest you running the package in Linux OS.

Best,
Shuzhan

**Comment by dannydarvish** [comment]
Thank you, Shuzhan! Indeed, my laptop has 32 GB of memory, which is much less than your 128 GB. I will try tuning those parameters and close the issue once I have been successful.

**Comment by dannydarvish** [comment]
While the smaller mesh sped up the execution significantly, it is still segfaulting. This could be a platform issue, so I will attempt to recompile and run on a Linux machine.

**Comment by dannydarvish** [comment]
I am reopening this issue. I have built gds2para on Ubuntu on a machine with 500gb of RAM. When I run the inverter example using mpirun, it segfaults, but when I run the executable directly without mpirun, it finishes without segfaulting.

**Comment by ShuzhanSun** [comment]
Hi Danny,

Michael @michaelhayashi is the main developer of MPI part. According to Michael, "the whole reason the code first used MPI was because [Hypre ](https://github.com/hypre-space/hypre) requires an MPI communicator in order to run".

In our Linux server, I have tested both command types `./LayoutAnalyzer -s examples/inv.gds examples/inv.sim_input test.cir` and `mpirun LayoutAnalyzer -s examples/inv.gds examples/inv.sim_input test.cir`. For the inverter example, both command types can successfully run through with MPI version:
- mpi/mpich-x86_64 
- mpi/mpich-3.0-x86_64
- mpi/mpich-3.2-x86_64

However, both command types did segfault with latest MPI version:
- mpi/openmpi3-x86_64


To help us debug your issue, Michael and I would like to find out three things with you:
1. Which version of MPI are you running?
2. Which flags are included in the ‘mpicxx’ alias?
3. Which Hypre version are you using?

Please share those information with us. Then, Michael and I will try to test them out asap.

Thanks,
Shuzhan

**Comment by dannydarvish** [comment]
Hi Shuzhan,

Thanks for your reply.

1. I am running Open MPI 2.1.1. I am attempting to install mpich now.
2. My mpicxx flags point to my normal GCC compilers, namely gcc-9, g++-9, and gfortran-9. (I assume you are talking about `OMPI_CC`, `OMPI_CXX`, and `OMPI_FC`.)
3. I am using Hypre version 2.20.0.

Edit: Built with mpich and segfaults indeed disappear.

**Comment by dannydarvish** [comment]
I was able to run the nand2 example with mpich without segfaults. However, the 1x1 resistance matrix just had `-nan` as a value, and there was a hypre error, shown below. Can you confirm if this is expected?

```
ERROR detected by Hypre ... BEGIN
ERROR -- hypre_FlexGMRESSolve: INFs and/or NaNs detected in input.
User probably placed non-numerics in supplied b.
Returning error flag += 101.  Program not terminated.
ERROR detected by Hypre ... END
```

**Comment by ShuzhanSun** [comment]
Hi Danny,

Thank you for pointing out the error at Hypre! The error is definitely not expected.

Since the start of this year, we have changed the solver engine to allow input of LEF/DEF files for 7-nm technology node. The new solver engine is still under development. Unfortunately, before each commit to the master branch, we did not test every existing example to guarantee backward compatibility.

The hypre error you saw at inverter example is because "Iterations = 100, Final Relative Residual Norm = nan". Looks like the iteration parameters were changed recently to accommodate the 7-nm node, but new parameters failed to catch previous larger tech node. I will go back to you when I find the solution. Will also update the code to fix the issue in next commit.

Thanks,
Shuzhan

Edit 03/09/2021: the error comes from missing metal conductivity in .sim_input files, not from iteration parameters.

**Comment by dannydarvish** [comment]
Thanks, Shuzhan. Is there a commit head you would recommend I revert to?

**Comment by ShuzhanSun** [comment]
Hi Danny,

About the Hypre error, I have contacted my advisor Prof. Dan Jiao, who made most recent changes on the solver engine. According to Prof. Jiao:
> "This is because the metal conductivity is not given in the input files. Since Jan. 30, the engine has been updated to take the conductivity from the .sim_input file instead of using the default copper conductivity. This is to make sure the computed resistance is correct. The nand2.sim_input file does not provide conductivity info, thus the engine took it as 0, and hence NAN error."

The solution is simple: provide the metal conductivity in sim_input files. I pushed a new commit just now, where all the sim_input files are updated. From your side, you only need to update your local repo accordingly. All existing examples are also re-tested. No error nor NAN is found anymore.

I would not recommend you to revert back, because an error in [RC extraction ](https://github.com/purdue-onchip/gds2Para/commit/46a24ecb5b5cd21692b9617b02f804513f1b2aeb) is fixed recently. However, if you do want to revert, you can revert back with command: 
```bash
git checkout `git rev-list -n 1 --before="2021-01-01 00:00" master`
```
I have tested it out and no Hypre error is found. But, please only use the Z-parameters in reverted version, do not use the extracted RC there.

Thanks,
Shuzhan

**Comment by dannydarvish** [comment]
Thank you for all the help, Shuzhan!
